
# Project Euler - Problem 2 -----------


#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

library(dplyr)

# First create a blank vector and set the first two in the sequence
f_sequence <- vector(mode="numeric", length=100)
f_sequence[1] <- 1
f_sequence[2] <- 2

# Second run a loop to calculate the next 98 numbers in the sequence
for (i in 3:1000) {
  f <- f_sequence[i-1] + f_sequence[i-2]
  f_sequence[i] <- f
} 

# Check you have made it big enough
f_sequence[100] # Yup plenty big enough

# Create functon which decides if even or odd
even <- function(x){
  x %% 2 == 0 }

# Data Wrangle
df_f_sequence <- as.data.frame(f_sequence) %>% 
  filter(f_sequence <=4000000) %>% 
  mutate(even_or_odd = even(f_sequence)) %>% 
  filter(even_or_odd == TRUE)

# Final Summation
sum(df_f_sequence$f_sequence)


